### PR TITLE
Cleanup + some features

### PR DESCRIPTION
**Pull request by BlackDark**
Should be merged after #13 

- Add custom config mount possiblity
- Change execution (no stopping the docker run command with ctrl + c works)
-

### CODE REVIEW

**Review by robertdebock — APPROVED** [review]
Looks great, thanks!

**Comment by robertdebock** [comment]
CI fails, I think it's not possible to generate a hash anymore:

```bash
docker run $(docker build -q .) /bin/sh -c "echo Password YoUrPaSsWoRd > /etc/cntlm.conf ; /usr/sbin/cntlm -H -u username -d mydomain"
```

Now returns: `USERNAME not defined.`

**Comment by BlackDark** [comment]
Ah, yeah. The password should be now generating secretly. I will check if can fix the test

**Comment by BlackDark** [comment]
Fixed the test :)

**Comment by robertdebock** [comment]
Thanks a lot @BlackDark!

**Pull request merged**
